export type ButtonVariant =
  | 'contained'
  | 'outlined'
  | 'cut-top'
  | 'cut-bottom'
  | 'white-dark'
  | 'white-red'
  | 'dark'
  | 'darkRed'
  | 'red'
  | 'w100'
  | 'skew'
  | 'large'
  | 'dashed'
  | 'curve'
  | 'curve-red'
  | 'curve-white'
  | 'curve-dark-small';
